version: "3.8"

services:
  mcp-sse-server:
    build: .
    container_name: mcp-sse-server
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:3333/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
